Introduce old commit "debug: special character in filenames" into GIT. Original commit time:  2013-02-16 17:31 +0800

diff --git a/bkgndxml b/bkgndxml
--- a/bkgndxml
+++ b/bkgndxml
@@ -1,81 +1,65 @@
 #!/bin/bash
 
-outfil=background.xml
-statc=1795.0
-trans=5.0
-filtyp="*.gif *.GIF *.jpg *.JPG *.png *.PNG *.bmp *.BMP"
-rndm=1
-dpth=30
+OutFil=background.xml
+Statc=595.0
+Trns=5.0
+FilTyp="gif|jpg|png|bmp"
+SortFil=Alphabetic
+# SortFil=Random
+Dpth=30
 
-rm -f tmpfl6395851
-for typs in $filtyp
-do
-  find $PWD -name "$typs" -maxdepth $dpth 1>> tmpfl6395851 2> /dev/null
-done
-filtol=$(wc -l tmpfl6395851 | cut -d " " -f1)
-if  [ $rndm -eq 1 ] ; then
-  sed 's/ /jTqd-_u/g' tmpfl6395851 | sort -R > tmpfl639585
-else
-  sed 's/ /jTqd-_u/g' tmpfl6395851 | sort > tmpfl639585
+ImgFils=$(
+  find $PWD -maxdepth $Dpth -regextype posix-extended \
+                      -iregex ".*\.($FilTyp)" 2> /dev/null )
+
+if  [ "$SortFil" == "Random" ] ; then
+  ImgFils=$( echo -e "$ImgFils" | sort -R )
+elif  [ "$SortFil" == "Alphabetic" ] ; then
+  ImgFils=$( echo -e "$ImgFils" | sort )
 fi
-rm -f tmpfl6395851
+
+filtol=$(echo -e "$ImgFils" | wc -l | cut -d " " -f1)
 
 if [ $filtol -gt 1 ] ; then
-  for img in $(cat tmpfl639585)
-  do
+  Yer=$(date +%Y)
+  Mnth=$(date +%m)
+  Day=$(date +%d)
+  Head="  <static>\n    <duration>$Statc</duration>\n    <file>"
+  Tail="</file>\n  </static>"
+  FrmHead="  <transition>\n    <duration>$Trns</duration>\n    <from>"
+  FrmTail="</from>"
+  ToHead="    <to>"
+  ToTail="</to>\n  </transition>"
 
-    if [ -z $previous ] ; then
-      first=$img
-      yer=$(date +%Y)
-      mnth=$(date +%m)
-      day=$(date +%d)
-      echo "<background>" > $outfil
-      echo "  <starttime>" >> $outfil
-      echo "    <year>$yer</year>" >> $outfil
-      echo "    <month>$mnth</month>" >> $outfil
-      echo "    <day>$day</day>" >> $outfil
-      echo "    <hour>00</hour>" >> $outfil
-      echo "    <minute>00</minute>" >> $outfil
-      echo "    <second>00</second>" >> $outfil
-      echo "  </starttime>" >> $outfil
-      echo "<!-- This animation will start at $yer/$mnth/$day 00:00. -->" >> $outfil
-      echo "  <static>" >> $outfil
-      echo "    <duration>$statc</duration>" >> $outfil
-      echo "    <file>$img</file>" >> $outfil
-      echo "  </static>" >> $outfil
+  (
+    echo "<background>"
+    echo "  <starttime>"
+    echo "    <year>$Yer</year>"
+    echo "    <month>$Mnth</month>"
+    echo "    <day>$Day</day>"
+    echo "    <hour>00</hour>"
+    echo "    <minute>00</minute>"
+    echo "    <second>00</second>"
+    echo "  </starttime>"
+    echo "<!-- This animation starts at $Yer/$Mnth/$Day 00:00. -->"
 
+    if [ "$Trns" == "0" ] ; then
+      echo -e "$ImgFils" | sed "s|^\(.*\)$|$Head\0$Tail|"
     else
-      if [ "$trans" != "0" ] ; then
-        echo "  <transition>" >> $outfil
-        echo "    <duration>$trans</duration>" >> $outfil
-        echo "    <from>$previous</from>" >> $outfil
-        echo "    <to>$img</to>" >> $outfil
-        echo "  </transition>" >> $outfil
-      fi
-      echo "  <static>" >> $outfil
-      echo "    <duration>$statc</duration>" >> $outfil
-      echo "    <file>$img</file>" >> $outfil
-      echo "  </static>" >> $outfil
+      FstFil=$( echo -e "$ImgFils" | head -n 1 )
+      echo -e "${Head}${FstFil}${Tail}"
+      echo -e "${FrmHead}${FstFil}${FrmTail}"
+      echo -e "$ImgFils" | tail -n +2 \
+       | sed "s|^\(.*\)$|$ToHead\0$ToTail\n$Head\0$Tail\n$FrmHead\0$FrmTail|"
+      echo -e "${ToHead}${FstFil}${ToTail}"
     fi
 
-  previous=$img
+    echo "</background>"
+  ) > $OutFil
 
-  done
-
-  if [ "$trans" != "0" ] ; then
-    echo "  <transition>" >> $outfil
-    echo "    <duration>$trans</duration>" >> $outfil
-    echo "    <from>"$PWD"/$img</from>" >> $outfil
-    echo "    <to>"$PWD"/$first</to>" >> $outfil
-    echo "  </transition>" >> $outfil
-  fi
-  echo "</background>" >> $outfil
-
-  mv $outfil a$outfil
-  sed 's/jTqd-_u/ /g' a$outfil > $outfil
-  rm -f a$outfil
-
+else
+  /usr/bin/zenity --warning --title="Error!" \
+     --text="Need two image files at least!"  > /dev/null 2>&1
+  echo -e "\nError!\nNeed two image files at least!\n"
+  exit 1
 fi
-
-unset outfil statc trans filtyp filtol img first previous dpth typs yer mnth day
-rm -f tmpfl639585
